export const Api = [
    {
        id: 0,
        destiny: "Your name does not have destiny number",
        dream: "Your name does not have dream number",
        soul: "Your name does not have soul urge number",

    },
    {
        id: 1,
        destiny: "Your destiny is to become #1 at all you do in your life.Your task is to develop your true, authentic self and to become in leader in whatever field you find you’re the most passionate and skilled.You’re all about power.You want to be the best at everything you do.You expect very high standards of performance from yourself and, in turn, also expect the same from others, which can set you up for frustration and disappointment.Your purpose is to take the lead and take initiative—the 1 Destiny number is not lack- luster or low - key! You’re meant to have courage, act independently on your unique and original ideas, be innovative, and take charge.All this while communicating and acting with clarity and compassion. ",
        dream: "The number one often shows a fresh start or signals a new beginning.One also represents you or a single person.Pay close attention if you see one because it might be signaling that you need to focus on your inner self more.It could also be asking you to consolidate all your energy on one single task or idea.",
        soul: "Your soul urges you to be the independent, leader type. You march to the beat of your own pa-rum-pum-pum-pum. You’re an intellectual. You set your standards for yourself pretty darn high and expect people to do the same for themselves. You aren’t willing to settle for anything less than what it is you desire and deserve. 1’s seem to work best in situations where they have both hands on the wheel, since it’s a surefire way to get to their desired destination.",

    },
    {
        id: 2,
        destiny: "Your destiny is to bring people together in an atmosphere of harmony and love.Your mission is to create harmony, balance, cooperation, and love wherever you go and in whatever you do.  Love is the cornerstone to your life and finding that perfect mate is important to you. You’re here to learn how to develop your sense of relationship;  how to successfully understand and relate to others and to yourself. Your path includes developing diplomacy.  Your 2 Destiny encourages you to seek to be of service to the “larger cause;” whether that’s your family, your company, or any other cause or group you feel strongly about.  Your destiny is to develop adaptability, open- hearted caring, and focus on the higher good.  Understand that you need to get out and socialize, because when you isolate yourself, you suffer from pessimism, depression, and inaction. ",
        dream: "Two is a number that represents balance.Seeing a two in your dreams might mean that it is time to decide about something in your life that has two options.It could also point to a need for balance in your life like your social interactions, your budget, or time.It might also look to a relationship in your life that needs attention.",
        soul: "Love is the battery back to the cutest little light that is your soul. When in alignment to your heart’s desires, you’re empathetic, loving, and patient. You’re maybe a little bit (or a lotta bit) indecisive, but it’s because deep down you want to make sure all parties are being accounted for and heard. You’re the ideal best friend and partner. Put THAT in your Tinder bio. You’re easily susceptible to people draining your energy, so protect yourself, especially when in large groups. 2’s thrive in areas where they’re making a positive impact on the world.",

    },
    {
        id: 3,
        destiny: "Your destiny is to inspire, motivate, heal, and uplift people.If you find you have a Destiny Number 3, you’re being called to inspire, heal, uplift, and energize others.  You’re all about performance, however that manifests for you in your life.  Your ultimate purpose comes through when you’re operating with a core sense of optimism, enthusiasm, compassion, and joy. Some of the qualities you bring to the table are beauty, possible eccentricity, excitement, and fame.  When you’ve tapped into your authentic sense of expression and then inspire others to use and express theirs, you’re fulfilling your life’s purpose.  If you give up on your dreams and don’t use your talents creatively, you’ll battle with depression and find yourself traveling down other unsatisfying or destructive pathways.  You must pursue your true calling, so make efforts to focus on what that is for you, believe in it and don’t be deterred from embracing it. ",
        dream: "Three is an indication of creativity.Seeing this number in your dreams is a sign that you need to create something.It can be art, music, a solution to a problem, or even a new identity.Your mind is ready to build and construct when it sees three.",
        soul: "The talkers, the movers, the shakers, the… bakers? Sure. If you’re expressing your true self, you’re in alignment with your soul’s urge. You have always dreamt of becoming influential. A celeb, perhaps? Prez? An author? Maybe becoming the winner of that hot dog eating contest on the 4th of July floats your big ‘ol boat? Whatever it is, go for it with your whole beautiful heart. You bring excitement wherever you go, and we love you for that. Believe in yourself, and believe that whatever dreams you have are bound to find you. It’s inevitable, 3.",

    },
    {
        id: 4,
        destiny: "Your destiny is to leave something of value that people can find beneficial in their day-to-day lives.You’re intent on building something of lasting value; whether that’s a family of your own, a business, or other enterprise.  You’re all about stability and security.  You’re hardworking, can be a pillar of your community, and are immanently trustworthy. In fact, honesty is a big issue for you.You have the potential to be a stellar marriage or business partner. Your life purpose revolves around being practical and hardworking.  You’re the systems-builder.  You’re the keeper of order and thrive on stability and security.  You might lean toward rigidness or stubbornness",
        dream: "Four is a very grounding number and provides stability and support.Different numbers have different meanings and different impacts on your life.It also points strongly to matters of the house because it can represent the four corners of your home.Maybe you’re thinking of buying a new home, or it’s time to organize and clean your current home.",
        soul: "Soul number 4’s are the types of people you want on your emergency contact list. You’re on time, organized, and strive for a lasting feeling of security. You have a strong work ethic and can achieve anything you set your mind to. You have an innate desire to build structure and order in the world, however that may manifest. The only limitation 4’s have is their own mind. Be fearless and trust yourself. Be mindful of taking care of yourself as much as you take care of others.",

    },
    {
        id: 5,
        destiny: "Your destiny is to effect change and show people how to live life to the maximum.The freewheeling 5 Destiny number pushes you toward a mission of adaptability, progress, freedom, and embracing the adventure of life.  Freedom is the guiding force in your life.  You thrive on hands-on experience.  You’re task is to develop your constructive use of freedom.Your purpose is to embrace your sense of fearlessness and follow your curiosity to explore the world and offer your magnetic presence and gifts to those around you. Most often the 5 Destiny number is intelligent, philosophical, and spiritually minded.You’re a natural salesperson when you’re dealing with something you believe in.  This Destiny number leads you on a roller coaster, where life can feel as though it’s coming at you without a filter.  Your destiny is one of liberation and freedom, no matter how you slice it. ",
        dream: "Five often represents the five elements and seeks to bring harmony into your life.It can also be an indication of motion or mobility.Don’t be surprised if you have the urge to travel or get out of town when you see the number five.",
        soul: "Your laughter and charisma are what draws people to you. Your wit and fearlessness is what keeps them around. Soul number 5’s have a tendency to be ferociously passionate about exploration, action, and thrills. It’s hard to nail you down, maybe even impossible. You move through life in a blur of bright color. You deeply enrich the lives of those around you without even realizing it. You’re always looking for what’s next, so try to remember to ground yourself in the perfection of the present moment.",

    },
    {
        id: 6,
        destiny: "Your destiny is to provide a nurturing safe ‘nest’ for yourself and your loved ones.Your mission is to nurture and serve, plain and simple.  Whether it’s your family and loved ones or your business or community, you are a master at creating beauty, harmony, and balance.  Love (shaken and stirred!) with acceptance is key for you as a 6 Destiny number. You have a polished presentation about you and denote an air of authority in whatever you do.  One of your specialties is damage control, so when things are moving along without trauma or drama, you have a tendency to either sweat it (while you wait for the other shoe to drop, so to speak) or you stir things up in order to have a problem to focus your energies on. Give yourself permission to accept things when life is good and smooth!  They’ll always be another problem to solve down the line.  No need to push it.",
        dream: "When you see the number six, it might be time to bring peace and balance to your family or relationships.The number six asks us to nurture those around us, such as children or partners, but also to self-indulge and care for our own spirit.",
        soul: "6’s are the types of people who always put others’ best interests before their own. You feel most fulfilled when providing emotional nourishment and tangible support to friends, family, children, animals, and even strangers. Your home is your nest, and you spend a great deal of time tending to it and making it reflect the inner you. You are deeply empathetic, sometimes to a fault. When you enter a space, people are enamored by your poise, comfort, and natural beauty. Your authentic, selfless personality is what sets you apart from the rest of the world. You’re a gifted teacher and healer. Never doubt the fact that you are loved unconditionally. Your purpose is to simply be yourself. Give yourself as much love as you give others for a lifetime of abundance and miracles.",

    },
    {
        id: 7,
        destiny: "Your destiny is to develop trust and faith and find your own answer to the meaning of life.As a 7 Destiny number, your mission is to seek out information and analyze it.  You’re all about knowledge and spiritual seeking. You dig deep and contemplate heavily.  You’re the perfect researcher and everything always comes back to informing your own sense of inner wisdom.  Your life-long task is to get to know the true you, inside and out.You need a good deal of private “alone” time.  Your life is instructed by a powerful collision between practical, tangible data and the analysis of it.  Then on the other hand, you’re highly intuitive and your gift—and your task—is to integrate the two (your intellect and your intuition) into a harmonious dance team. ",
        dream: "In numerology, seven is a profoundly mystical number.It has a certain magic to it that calls to a higher level of knowledge.If you see a number seven in your dreams, seek out more enlightenment and education.",
        soul: "You are deeply introspective, observant, and contemplative. You retreat to nature in times of inner and outer distress, and find the most comfort in alone time. 7’s are in a league of their own. You’re one of a kind, but also scared of being misunderstood, so you find yourself torn between wanting to fit in and dying to stand out. You dive deeper within yourself to discover who you truly are than anyone else on this list. The good news is - the answers you seek to life are already within you. You have the gift of not only knowledge, but wisdom - so trust yourself! You are a direct extension of the universe.",

    },
    {
        id: 8,
        destiny: "Your destiny is to manifest financial security that allows you freedom to make a difference in the world.An 8 Destiny number is calling for you to gain self-mastery in a profound way.  Your purpose is to achieve and succeed with business and organization—not to mention personal power, control, authority, and above all, ethics.  The Eight is a relentless taskmaster and demands that you understand and employ all your abilities to achieve financial abundance and also to give to others generously.  When you realize that you’re here to achieve power and abundance and then act on that knowledge, your destiny will be fulfilled. Right out of the gate, you have authority issues.",
        dream: "The number eight is a unique number to see in a dream because it is usually the way the universe conveys that it is always caring for us.Eight shares the same significance with the infinite nature and cycles of life.It points to everything in your life being in order and the knowledge that everything will work out in due time.",
        soul: "8 is the number of infinity and abundance. You’re the face of wealth, health, and success, whether or not that’s tangible yet. You’re destined to be financially free as your soul thrives from giving to others. Make note of what it is that makes your heart sing, and follow suit. People sense your natural authoritative energy as you walk into a room. Use that to your advantage and step into your power.",

    },
    {
        id: 9,
        destiny: "Your destiny is to achieve a higher state of consciousness and teach others how to achieve theirs.Your mission is a humanitarian one.  Yours is a spiritual path and you’re here to love unconditionally, however that may manifest in your life. You’re often a hopeless romantic at heart and can set yourself up for disappointment when people don’t measure up to your ideals.   You’re at your optimal when you’re tapping into your creativity, sensitivity, and selflessness.Beware that others may find that you’re ideas are a little on the cuckoo-side! This Destiny number is a powerful one demanding that you learn to transform and heal (both yourself and others) while letting go of the past freely and without bitterness. ",
        dream: "People experience significant changes in their lives, but patterns often exist throughout. The number nine in dreams may symbolize the constants in your life; those aspects that remain the same in spite of change.",
        soul: "As a number 9, you’re considered the old soul. People usually think you’ve got it all together, even if you yourself know you don’t. Even though you’re a fantastic friend, it’s often hard for you to ask them for help since giving to others is so ingrained in your DNA. There’s no need to feel guilty for asking for a hand with something. Take the pressure off yourself, give yourself permission to support people from a safe distance rather than feeling responsible for everyone’s well being. Your soul urges you to accept the love the universe wants to give you.",

    },
    {
        id: 11,
        destiny: "Your destiny is to heal and transform others through selfless service and artistic creativity.Your special mission is to recognize and use your creativity, intuition, and healing abilities for the benefit of humanity as a whole.  You can achieve this in a multitude of ways—eliciting an emotional response through dance, music, or art.  Working one-on-one or in groups with various healing modalities.  Or you can write, entertain, teach. Remember, you are a double 1 (leadership, confidence) and yet also a 2 (harmony, love).  So you come with some special challenges to fulfill your mission.  A 2 Life Path will go out of their way to avoid being in the spotlight.  A 2 is most at peace and satisfied when they’re taking the reins behind the scenes.  The 11 pushes you into the spotlight and this will have some disconcerting effects on you.  You’ll feel as though nothing you do is ever quite enough.  You’ll have a nervous energy that you just can’t control.  You’ll lean toward impatience and criticism (toward yourself and others) and arm-wrestle with self-doubt.",
        dream: "It stands for balance, duality, wisdom, and enlightenment. Through the number 11, the guardian angels want you to share your perspective of life with others around you. The master number 11 meaning is that many could learn from you because you're wise. You should step up and show the leadership that's in you",
        soul: "The first of the master numbers. 11’s are profound creatives and feel most fulfilled in a balance between analytics and art. Your soul expresses both the qualities of 1’s (independence, drive) and 2’s (grace, love). You’ve been through so much in your life, which has shaped you to be the empathetic, noble leader you are. You’re sensitive and personable, enough to make friends with anyone. It might be hard for you to see how talented you are, so try not to doubt yourself. You’re sometimes torn between wanting to be on the court (1’s) and wanting to be on the bench (2’s) so you have a habit of dulling your sparkle. Let your true self shine and the rest will happen effortlessly.",

    },
    {
        id: 22,
        destiny: "Your destiny is to bring forth masterful teaching and inspired practical ideas.Your mission as a Master number is to execute and build projects that will benefit a wide arena of humankind.  This is a spiritual path (like all the Master numbers) that prods you to step out of the slow, steady security of the number 4 and kick it up substantially.  This will be uncomfortable for you until you get the hang of it, because it’s contrary to the pull you have with the rule-following energy of the 4.You’ll use all the hardworking, step-by-step qualities of the Four while tapping into a higher level of purpose and action.  You’ll learn to take risks and look toward setting higher stakes with your enterprises.  You’re the Master Builder extraordinaire, so look toward building solid foundations to your enterprise with the big picture in front of you at all times. ",
        dream: "Angel number 22 has the energies of your dreams and deepest desires. It is believed that if you keep seeing them, then you are on your way to achieving your dreams. Angel number 22 also represents harmony and balance. This means that things that disturb your life's balance will be gone",
        soul: "The second of the master numbers. Your soul possesses both the characteristics of 2’s (grace, love) and 4’s (precise, grounded). 22’s spiritual path includes learning to work smart, not hard, while creating a sustainable impact on the world. You are urged to utilize your ambition and creativity to bring your bright ideas to life. 22’s feel fulfilled when they are of service to the things that matter to them. Like the number 4, you chase the sense of security. Being a double 2 means you have double the 2 power, and are doubly susceptible to energy vampires. Protect your heart without watering down your light.",

    },
    {
        id: 33,
        destiny: "This is a challenge from the get-go.  If you find yourself with a 33 Destiny number, your mission (should you choose to accept it! . . . cue Mission Impossible music . . . ) is to be a Master Healer and to bring forth a higher form of love to the world.  Since you have the double 3’s, you also have to do this with joy, fun, and heart-felt communication and expression.It’s your calling to teach and show by example the power of love.  You’re meant to serve as a conduit to healing on whatever level you feel most compelled to engage.  The Master number presupposes that you’ll take on leadership positions and the 33/6 encompasses visionary goals, truth and beauty, and a nurturing and giving heart.",
        dream: "When you see angel number 33, it is a clear sign that the angels are with you, which means that they will bring love and peace into your life. If you are seeing angel number 33 very often, it means that the angels are waiting for you to call them. They want to answer to your prayers and to help you.",
        soul: "The third master number. 33’s are a magnified soul number 3, and also possess characteristics of the 6. You feel everything so deeply with an intense urgency. You absorb whatever energy you encounter which can be detrimental to your well-being. Your soul urge is to help others see the beauty that life has to offer. You wish for everyone to experience unconditional love and do whatever it takes to put a smile on someone’s face. 33 is an intense number, one that may lead to unhealthy coping mechanisms. Practice self care through movement, art, and affirmations.",

    }
]